### ISSUE TITLE
0.7_1 no available servers

### ISSUE THREAD

**Issue by joeroback** [mihakralj/opnsense-speedtest#3]
```
# opnsense-version
OPNsense 21.1.3_3 (amd64/OpenSSL)
# pkg info | grep speedtest
os-speedtest-0.7_1             OPNsense plugin for speedtest
speedtest-1.0.0.2-1.5ae238b    no description given
```

Command line listing of servers works.
```
# speedtest --servers
Closest servers:

    ID  Name                           Location             Country
==============================================================================
 38478  AU Wireless                    Golden, CO           United States
  8862  CenturyLink                    Denver, CO           United States
 16797  Nitel                          Denver, CO           United States
 10051  Comcast                        Denver, CO           United States
 23628  Whitesky Communications        Denver, CO           United States
 14861  Aerux Broadband                Denver, CO           United States
 24079  ALLO - Denver                  Denver, CO           United States
 20818  Verso Networks                 Denver, CO           United States
 26545  Mean Servers                   Denver, CO           United States
 19124  Vistabeam                      Denver, CO           United States
```

![image](https://user-images.githubusercontent.com/156174/112655855-6fbcc900-8e16-11eb-9c1b-00a027aae9a7.png)

**Comment by joeroback** [comment]
When I load the `Reporting: Speedtest` page with the JavaScript console open.. I see this:
![image](https://user-images.githubusercontent.com/156174/112656135-b3afce00-8e16-11eb-9536-171b7a93c565.png)

**Comment by mihakralj** [comment]
let's troubleshoot from CLI forward:
1. cli: `speedtest -L -fjson`   (seems like it works)
2.  Python wrapper: `sudo /usr/local/opnsense/scripts/OPNsense/speedtest/opn_speedtest.py list` (should return the same list)
3. API call: http://<firewall>/api/speedtest/service/serverlist (should return the same json list)
4. this API is then called (and consumed) by ajax call in GUI

Step 2 or 3 should be broken for you, it seems. Which one?

**Comment by joeroback** [comment]
http:///api/speedtest/service/serverlist? But the screenshot of the javascript console seems to be looking for http:///api/speedtest/service/server/list

serverlist vs server/list

I've tried shift-reloading.. it seems like the index.volt template is not being reloaded somehow?

Looking at the source of the webpage:
![image](https://user-images.githubusercontent.com/156174/112658644-36398d00-8e19-11eb-8a5e-e1f640963380.png)

Both looking what is installed looks good:
```
# egrep -srIn serverlist /usr/local/opnsense/mvc/app/views/OPNsense/Speedtest
/usr/local/opnsense/mvc/app/views/OPNsense/Speedtest/index.volt:221:                ajaxCall(url = "/api/speedtest/service/serverlist", sendData = {}, callback = function(l, status) {
```

---

```
# speedtest -L -fjson
{"type":"serverList","timestamp":"2021-03-26T15:47:25Z","servers":[{"id":38478,"name":"AU Wireless","location":"Golden, CO","country":"United States","host":"speedtest.auwireless.net","port":8080},{"id":8862,"name":"CenturyLink","location":"Denver, CO","country":"United States","host":"denver.speedtest.centurylink.net","port":8080},{"id":16797,"name":"Nitel","location":"Denver, CO","country":"United States","host":"speedtest.den1.nitelusa.net","port":8080},{"id":10051,"name":"Comcast","location":"Denver, CO","country":"United States","host":"stosat-dvre-01.sys.comcast.net","port":8080},{"id":23628,"name":"Whitesky Communications","location":"Denver, CO","country":"United States","host":"speedtest.dnvr.co.wtsky.net","port":8080},{"id":14861,"name":"Aerux Broadband","location":"Denver, CO","country":"United States","host":"sp1.aerux.com","port":8080},{"id":24079,"name":"ALLO - Denver","location":"Denver, CO","country":"United States","host":"den11-speedtest01.as15108.com","port":8080},{"id":26545,"name":"Mean Servers","location":"Denver, CO","country":"United States","host":"speedtest.den01.meanservers.net","port":8080},{"id":20818,"name":"Verso Networks","location":"Denver, CO","country":"United States","host":"speedtest.versonetworks.net","port":8080},{"id":19124,"name":"Vistabeam","location":"Denver, CO","country":"United States","host":"ookla-denver.vistabeam.com","port":8080}]}
```
```
# /usr/local/opnsense/scripts/OPNsense/speedtest/opn_speedtest.py list
[{"id": "38478", "name": "AU Wireless", "location": "Golden, CO", "country": "United States"}, {"id": "8862", "name": "CenturyLink", "location": "Denver, CO", "country": "United States"}, {"id": "16797", "name": "Nitel", "location": "Denver, CO", "country": "United States"}, {"id": "10051", "name": "Comcast", "location": "Denver, CO", "country": "United States"}, {"id": "23628", "name": "Whitesky Communications", "location": "Denver, CO", "country": "United States"}, {"id": "14861", "name": "Aerux Broadband", "location": "Denver, CO", "country": "United States"}, {"id": "24079", "name": "ALLO - Denver", "location": "Denver, CO", "country": "United States"}, {"id": "20818", "name": "Verso Networks", "location": "Denver, CO", "country": "United States"}, {"id": "26545", "name": "Mean Servers", "location": "Denver, CO", "country": "United States"}, {"id": "19124", "name": "Vistabeam", "location": "Denver, CO", "country": "United States"}]
```

**Comment by joeroback** [comment]
When I look at the list of installed templates, I don't see speedtest...
```
# configctl template list
OPNsense/AcmeClient [2]
OPNsense/Auth [5]
OPNsense/Captiveportal [4]
OPNsense/Cron [1]
OPNsense/Filter [2]
OPNsense/IDS [10]
OPNsense/IPFW [2]
OPNsense/MDNSRepeater [1]
OPNsense/Macros [0]
OPNsense/Monit [2]
OPNsense/Netflow [5]
OPNsense/Nginx [8]
OPNsense/Nut [7]
OPNsense/Proxy [15]
OPNsense/Sample [2]
OPNsense/Sample/sub1 [1]
OPNsense/Sample/sub2 [1]
OPNsense/Syslog [8]
OPNsense/Syslog/local [0]
OPNsense/Syslog/sources [0]
OPNsense/Unbound [0]
OPNsense/Unbound/core [4]
OPNsense/Vnstat [2]
OPNsense/WebGui [2]
OPNsense/Wireguard [2]
```
So I am unable to issue a `configctl template reload OPNsense/Speedtest` or similar

**Comment by joeroback** [comment]
```
# configctl webgui restart
```
Then I reloaded the page and fixed.
![image](https://user-images.githubusercontent.com/156174/112659911-7ea57a80-8e1a-11eb-8699-8a0339f831d4.png)

**Comment by mihakralj** [comment]
you have an old version of `index.volt` file in `/usr/local/opnsense/mvc/app/views/OPNsense/Speedtest` - I consolidated the naming of APIs to be more consistent - list of servers used to be /list, but is now /serverlist.

1. how the heck did you get an old index.volt? The one in the source tree (and in the package) is updated...
2. I don't store any data in config.xml therefore I use no models and generate no templates. :-)
3. you can refresh the phalcon Volt engine by `configctl webgui restart`

**Comment by joeroback** [comment]
I dont have an old version, I showed you the `grep`

**Comment by joeroback** [comment]
maybe the installer needs to issue a webgui restart? so that it picks up any more template changes?

**Comment by joeroback** [comment]
ok, i tried running a speedtest and now this...
![image](https://user-images.githubusercontent.com/156174/112660297-e78cf280-8e1a-11eb-81e1-c1db35aab603.png)

**Comment by joeroback** [comment]
I just re-ran it and it worked? 🤷🏼 maybe it would be nice to output the json to the console on error?

**Comment by mihakralj** [comment]
Same process of troubleshooting:
- cli: speedtest -fjson
Python wrapper: `sudo /usr/local/opnsense/scripts/OPNsense/speedtest/opn_speedtest.py 38478`  
API call: `http:///api/speedtest/service/run/38478`

**Comment by mihakralj** [comment]
you have some stale cache problems...

**Comment by joeroback** [comment]
Note you also have an issue with the widget,
https://github.com/mihakralj/opnsense-speedtest/blob/f9a4e34ae1c1b5cff2ae7edd2018dc603c8e2435/src/www/widgets/widgets/speedtest.widget.php#L3

you didn't update the URL...

**Comment by joeroback** [comment]
BTW, thanks for doing this, its really nice addon to OPNsense. I guess with zero tests, you are going have these rough releases...

**Comment by mihakralj** [comment]
this one on Widget is a legit bug. should be `/api/speedtest/service/serverstat`
Thanks!

**Comment by joeroback** [comment]
I mean, isn't there also an issue that the any volt template changes need to issue a webgui restart as well?

**Comment by mihakralj** [comment]
correct. any change to .volt requires a restart of webgui...
I have an alias made for `sudo service configd restart && sudo configctl webgui restart` - that I fire every time I change anything on my development box...

**Comment by joeroback** [comment]
So if I just change the URL for widget, the output from calling that directly in browser
```
{"samples": 2, "period": {"oldest": "2021-03-26 16:07:24", "youngest": "2021-03-26 16:07:53", "days": 0}, "latency": {"avg": 3.63, "min": 2.85, "max": 4.41, "last": 729.34}, "download": {"avg": 666.07, "min": 602.8, "max": 729.34, "last": 933.01}, "upload": {"avg": 932.5, "min": 932.0, "max": 933.01, "last": 2.85}}
```
But the dashboard
![image](https://user-images.githubusercontent.com/156174/112662054-d8a73f80-8e1c-11eb-9356-c29ae2a584ae.png)

I've tried clearing my cache, webgui restart, etc, etc and always the same issue

**Comment by mihakralj** [comment]
```
<script>
    function stat_reload(){
        ajaxCall(url="/api/speedtest/service/showstat", sendData={}, callback=function(l,status) {
            $('#stat_samples').html("<b>"+l.samples+"<\/b>")
            $('#stat_latency').html("<b>"+l.latency.avg+" ms<\/b><small> (min: "+l.latency.min+" ms, max: "+l.latency.max +" ms)</small>")
            $('#stat_download').html("<b>"+l.download.avg+" Mbps<\/b><small> (min: "+l.download.min+" Mbps, max: "+l.download.max +" Mbps)</small>")
            $('#stat_upload').html("<b>"+l.upload.avg+" Mbps<\/b><small> (min: "+l.upload.min+" Mbps, max: "+l.upload.max +" Mbps)</small>")
        });
    };
    $(window).on("load", function() {
        stat_reload();
    });
</script>

<!-- gateway table -->
<table id="speedtest_widget_table" class="table table-striped table-condensed">
  <tr>
      <td>Avg Latency:</td>
      <td><div id="stat_latency">0.00 ms (min: 0.00 ms, max: 0.00 ms)</div>
      </td>
  </tr>
  <tr>
      <td>Avg Download:</td>
      <td><div id="stat_download">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div>
      </td>
  </tr>
  <tr>
      <td>Avg Upload:</td>
      <td><div id="stat_upload">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div>
        </td>
  </tr>
</table>

```

**Comment by mihakralj** [comment]
as I said, all APIs now return direct json, no longer {"response":"stuff"} wrapper. So, no need anymore to do json-ification of the response. I didn't fix it for widget...

**Comment by joeroback** [comment]
Looking at the response, I get a 403. If I remove the JavaScript named parameters... I am using the latest Chrome browser. If I remove them
```
ajaxCall("/api/speedtest/service/showstat", {}, function(data,status) {
```
![image](https://user-images.githubusercontent.com/156174/112663322-4bfd8100-8e1e-11eb-922c-9b728479f430.png)

No errors and widget works..

**Comment by joeroback** [comment]
I put the named params back...
![image](https://user-images.githubusercontent.com/156174/112663730-c75f3280-8e1e-11eb-8d20-c6c38a0e68b3.png)

**Comment by mihakralj** [comment]
the exact same call is used in volt template and clearly works in your browser... wth?

**Comment by joeroback** [comment]
oh, sorry, my bad, i had `snedData=` instead of `sendData=` .. and now its all working.. geez i thought i was going crazy there for moment..

**Comment by mihakralj** [comment]
cleaned-up widget code:
```
<script>
    $(window).on("load", function() {
        ajaxCall("/api/speedtest/service/showstat", {}, function(l,status) {
            $('#stat_samples').html("<b>"+l.samples+"<\/b>")
            $('#stat_latency').html("<b>"+l.latency.avg+" ms<\/b><small> (min: "+l.latency.min+" ms, max: "+l.latency.max +" ms)</small>")
            $('#stat_download').html("<b>"+l.download.avg+" Mbps<\/b><small> (min: "+l.download.min+" Mbps, max: "+l.download.max +" Mbps)</small>")
            $('#stat_upload').html("<b>"+l.upload.avg+" Mbps<\/b><small> (min: "+l.upload.min+" Mbps, max: "+l.upload.max +" Mbps)</small>")
        });
    });
</script>
<table id="speedtest_widget_table" class="table table-striped table-condensed">
  <tr><td>Avg Latency:</td><td><div id="stat_latency">0.00 ms (min: 0.00 ms, max: 0.00 ms)</div></td></tr>
  <tr><td>Avg Download:</td><td><div id="stat_download">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div></td></tr>
  <tr><td>Avg Upload:</td><td><div id="stat_upload">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div></td></tr>
</table>
```

**Comment by joeroback** [comment]
ok now looks like all things are working! the named parameters do work, i had a typo, sorry. Javascript 6 looks like its supported by browsers starting 2016, so i dont think its an issue using them..

**Comment by mihakralj** [comment]
another cosmetic change (column width):
I'll put this one into the next release.
```
<script>
    $(window).on("load", function() {
        ajaxCall("/api/speedtest/service/showstat", {}, function(l,status) {
            $('#stat_samples').html("<b>"+l.samples+"<\/b>")
            $('#stat_latency').html("<b>"+l.latency.avg+" ms<\/b><small> (min: "+l.latency.min+" ms, max: "+l.latency.max +" ms)</small>")
            $('#stat_download').html("<b>"+l.download.avg+" Mbps<\/b><small> (min: "+l.download.min+" Mbps, max: "+l.download.max +" Mbps)</small>")
            $('#stat_upload').html("<b>"+l.upload.avg+" Mbps<\/b><small> (min: "+l.upload.min+" Mbps, max: "+l.upload.max +" Mbps)</small>")
        });
    });
</script>
<table id="speedtest_widget_table" class="table table-striped table-condensed">
  <tr><td style="width:25%">Avg Latency:</td><td><div id="stat_latency">0.00 ms (min: 0.00 ms, max: 0.00 ms)</div></td></tr>
  <tr><td>Avg Download:</td><td><div id="stat_download">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div></td></tr>
  <tr><td>Avg Upload:</td><td><div id="stat_upload">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div></td></tr>
</table>
```

**Comment by joeroback** [comment]
one thing to consider, is `ajaxGet` vs `ajaxCall`, get uses `GET` vs call using `POST`, since you aren't posting any data.
https://docs.opnsense.org/development/frontend/view_js_helpers.html#ajaxget

**Comment by joeroback** [comment]
Also one more minor thing, if you clear the logs, # of probes shows `undefined` instead of `0`
![image](https://user-images.githubusercontent.com/156174/112668344-06dc4d80-8e24-11eb-9978-ac22ca0962a3.png)

**Comment by mihakralj** [comment]
Fixed that one too; I wanted to implement something that would correlate the last test data with the averages - and left some unfinished code in my Python wrapper. I cut it out for now

**Comment by mihakralj** [comment]
I did the changes and pushed the updated version - could you pls check if all is in order?

**Comment by joeroback** [comment]
With the same version? and not `0.7_2`?

**Comment by joeroback** [comment]
with the `ajaxCall` I still see 403's on the ajax calls
![image](https://user-images.githubusercontent.com/156174/112709642-cfe85500-8e80-11eb-9ac0-682aa805c5fa.png)

If i change it to `ajaxGet` it works immediately, no webgui restart, no clear cache, etc, just plain-old page refresh
![image](https://user-images.githubusercontent.com/156174/112709663-045c1100-8e81-11eb-85b1-5af81f00a37d.png)

**Comment by joeroback** [comment]
I have been running with `ajaxGet` for couple of days now and its great! Widget is working great too!
![image](https://user-images.githubusercontent.com/156174/112915195-0ad5cd00-90bb-11eb-9586-840a4998d8a4.png)
![image](https://user-images.githubusercontent.com/156174/112915202-10cbae00-90bb-11eb-99ab-1ae6ed414d2e.png)

**Comment by mihakralj** [comment]
I switched the widget from using ajax to use PHP that bypasses all API and js magic. Works on mobile phone and generates dashboard much faster.

Pls check... :-)

**Comment by joeroback** [comment]
I guess now the widget doesn't refresh. Lots of the existing widgets use `ajaxGet` and `ajaxCall`, you just have to be more careful with `ajaxCall` as the `POST` is a little bit more sensitive it seems.

I've been running `ajaxGet` now for 7 days and it works great BTW. not a little error and i have the dashboard up 24/7

**Comment by mihakralj** [comment]
Does it work on mobile?

**Comment by joeroback** [comment]
yea, it worked on chrome on iOS (the only thing i tested), but i guess as it was in 0.7 it didn't refresh either, it just used ajax on page load anyways so maybe straight PHP is the way to go if you are not going to implement a refresh (which is probably fine for speedtest widget).

Any reason why you are calling the python directly instead of using `configd_run(...)` to go through the API? Seems to be what most other widgets do if they are using PHP.

**Comment by mihakralj** [comment]
I am not storing anything in conf/config.xml. My apis are pointing to configctl that then calls python code. It somehow made sense when I designed it, but I don't know why. 😊

Running a full-time dashboard that auto-refreshes... Without a menu sidebar... And with better layout with more charts...

I was thinking of this a while ago, even added plotly.js into one of my experiments. This might be a fun project.

**Comment by joeroback** [comment]
yea, i think one of the major upsides to OPNsense vs pfSense is the ability to use an API. I personally think you should be using the API as per the documentation, because if someone else wants to write a script or a report, etc, they can use the API to query the results, fire off new runs, etc, without having to figure out your python or maybe you switch to bash/sh or php in the future, the API is stable... you are free to implement the backend as you see fit, etc

**Comment by mihakralj** [comment]
I tried with php and a direct call of python code and - while blazingly fast - it indeed doesn't refresh...

**Comment by joeroback** [comment]
yea, that is why ajax was invented, for asynchronous updates on websites... i mean the API for stat returns a few bytes of data, even on a VM running OPNsense a Pentium Silver J5005 CPU its fast...

**Comment by mihakralj** [comment]
Another plugin and widget that I started to work on - and might interest you:
- pulling data from vpnapi.io, ipapi.com, ipqualityscore.com, ipblacklist.ai, and hetrixtools.com - and show the 'outside-in' view of the OPNsense: visible IPv4 and IPv6 address, potential blacklistings, is it recognized as VPN/Proxy/Tor, what ports are open from the outside.

**Comment by mihakralj** [comment]
ok, I am trying to recover the old Ajax widget... Do you mind pasting your working .widget here?

**Comment by joeroback** [comment]
```
<script>
    $(window).on("load", function() {
        ajaxGet("/api/speedtest/service/showstat", {}, function(l,status) {
            $('#stat_samples').html("<b>"+l.samples+"<\/b>")
            $('#stat_latency').html("<b>"+l.latency.avg+" ms<\/b><small> (min: "+l.latency.min+" ms, max: "+l.latency.max +" ms)</small>")
            $('#stat_download').html("<b>"+l.download.avg+" Mbps<\/b><small> (min: "+l.download.min+" Mbps, max: "+l.download.max +" Mbps)</small>")
            $('#stat_upload').html("<b>"+l.upload.avg+" Mbps<\/b><small> (min: "+l.upload.min+" Mbps, max: "+l.upload.max +" Mbps)</small>")
        });
    });
</script>
<table id="speedtest_widget_table" class="table table-striped table-condensed">
  <tr><td style="width:25%">Avg Latency:</td><td><div id="stat_latency">0.00 ms (min: 0.00 ms, max: 0.00 ms)</div></td></tr>
  <tr><td>Avg Download:</td><td><div id="stat_download">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div></td></tr>
  <tr><td>Avg Upload:</td><td><div id="stat_upload">0 Mbps (min: 0 Mbps, max: 0 Mbps)</div></td></tr>
</table>
```

i think that was what i had, i installed your latest and lost my changes, sorry.

**Comment by joeroback** [comment]
also note from https://docs.opnsense.org/development/frontend/view_js_helpers.html instead of `$(window).on("load", ...)` it uses `ready()` which maybe more compatible across browsers and platforms...

```
<script>
$( document ).ready(function() {
   ...
});
</script>
```

**Comment by mihakralj** [comment]
in case you missed it, the plugin is now part of mimugmail repo for OPNSense...
https://github.com/mimugmail/opn-repo 

```
sudo fetch -o /usr/local/etc/pkg/repos/mimugmail.conf https://www.routerperformance.net/mimugmail.conf
sudo pkg update
```
